<a href="https://colab.research.google.com/github/minhaz1172/Deep-Learning-with-PyTorch/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset,DataLoader
from nltk.tokenize import word_tokenize
import nltk

# Create A documnet

In [102]:
document= """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

# Tokenization

In [103]:
# Tokenization
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [104]:
tokens=word_tokenize(document)
tokens=(token.lower() for token in tokens)

# Build Vocab

In [105]:
vocab={'<unk>':0}
token_counts=Counter(tokens)


In [106]:
vocab = {'<unk>': 0}

for token, freq in token_counts.items():
    if token not in vocab:
        new_index = len(vocab)
        vocab[token] = new_index
        print(f"Adding token {token!r} at index {new_index}")

print("\nFinal vocab mapping:")
for t, i in vocab.items():
    print(f"{t!r} → {i}") # giving index to tokens


Adding token 'about' at index 1
Adding token 'the' at index 2
Adding token 'program' at index 3
Adding token 'what' at index 4
Adding token 'is' at index 5
Adding token 'course' at index 6
Adding token 'fee' at index 7
Adding token 'for' at index 8
Adding token 'data' at index 9
Adding token 'science' at index 10
Adding token 'mentorship' at index 11
Adding token '(' at index 12
Adding token 'dsmp' at index 13
Adding token '2023' at index 14
Adding token ')' at index 15
Adding token 'follows' at index 16
Adding token 'a' at index 17
Adding token 'monthly' at index 18
Adding token 'subscription' at index 19
Adding token 'model' at index 20
Adding token 'where' at index 21
Adding token 'you' at index 22
Adding token 'have' at index 23
Adding token 'to' at index 24
Adding token 'make' at index 25
Adding token 'payments' at index 26
Adding token 'of' at index 27
Adding token 'rs' at index 28
Adding token '799/month' at index 29
Adding token '.' at index 30
Adding token 'total' at index 31


In [107]:
vocab_size=len(vocab)
print(vocab_size)

288


# extract sentences from data

In [108]:
input_sentence=document.split('\n')

In [109]:
def text_to_indices(sentence,vocab):
  numerical_sentence=[]

  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])

    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [110]:
input_numerical_sentence=[]
for sentence in input_sentence:
  input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()),vocab))
print(input_numerical_sentence)

[[1, 2, 3], [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15], [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28, 29, 30], [4, 5, 2, 31, 32, 27, 2, 6, 33], [2, 31, 32, 27, 2, 6, 5, 34, 35, 30, 36, 2, 31, 6, 7, 37, 38, 39, 34, 40, 28, 41, 12, 42, 30, 15], [4, 5, 2, 43, 27, 2, 11, 3, 33], [44, 45, 46, 47, 2, 48, 49, 50], [51, 52], [51, 53, 8, 9, 10], [9, 54], [55, 8, 9, 10], [56, 8, 57, 58], [59, 60], [61, 59], [62], [63, 64], [22, 65, 66, 2, 67, 43, 68, 69, 70, 50, 71], [45, 72, 58, 73, 74, 46, 17, 75, 27, 76, 3, 33], [77, 78, 74, 73, 72, 58, 79, 80, 81, 17, 75, 27, 76, 3, 82, 83, 84, 30], [4, 85, 86, 87, 17, 88, 89, 33, 45, 86, 90, 17, 91, 27, 2, 89, 33], [92, 93, 94, 95, 80, 96, 78, 36, 97, 85, 22, 87, 17, 89, 22, 65, 98, 99, 73, 100, 2, 91, 30], [21, 65, 86, 101, 2, 102, 103, 33], [104, 76, 105, 106, 24, 107, 108, 109, 108, 110, 111, 27, 2, 6, 69, 70, 50, 112, 33, 113, 30], [4, 5, 2, 110, 32, 27, 93, 2, 88, 95, 33], [114, 78, 93, 2, 95, 115, 116, 117, 30], [4, 5, 2, 118, 1

In [111]:
len(input_numerical_sentence)

78

# Convert all sentence to training sequence form(as next word predictor)

In [112]:
for sentence in input_numerical_sentence:
  for i in range(1,len(sentence)):
    print(sentence[:i+1]) # print first sentence in training sequence first sequence(1->2),2nd sequence(2->3)
  break

[1, 2]
[1, 2, 3]


# print all sequence

In [113]:
for sentence in input_numerical_sentence:
  for i in range(1,len(sentence)):
    print(sentence[:i+1]) # print first sentence in training sequence first sequence(1->2),2nd sequence(2->3)

[1, 2]
[1, 2, 3]
[4, 5]
[4, 5, 2]
[4, 5, 2, 6]
[4, 5, 2, 6, 7]
[4, 5, 2, 6, 7, 8]
[4, 5, 2, 6, 7, 8, 9]
[4, 5, 2, 6, 7, 8, 9, 10]
[4, 5, 2, 6, 7, 8, 9, 10, 11]
[4, 5, 2, 6, 7, 8, 9, 10, 11, 3]
[4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12]
[4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13]
[4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14]
[4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15]
[2, 6]
[2, 6, 16]
[2, 6, 16, 17]
[2, 6, 16, 17, 18]
[2, 6, 16, 17, 18, 19]
[2, 6, 16, 17, 18, 19, 20]
[2, 6, 16, 17, 18, 19, 20, 21]
[2, 6, 16, 17, 18, 19, 20, 21, 22]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28, 29]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 

# training sequence in list

In [114]:
training_sequence=[]
for sentence in input_numerical_sentence:
  for i in range(1,len(sentence)):
    training_sequence.append(sentence[:i+1])

In [115]:
print(training_sequence)

[[1, 2], [1, 2, 3], [4, 5], [4, 5, 2], [4, 5, 2, 6], [4, 5, 2, 6, 7], [4, 5, 2, 6, 7, 8], [4, 5, 2, 6, 7, 8, 9], [4, 5, 2, 6, 7, 8, 9, 10], [4, 5, 2, 6, 7, 8, 9, 10, 11], [4, 5, 2, 6, 7, 8, 9, 10, 11, 3], [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12], [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13], [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14], [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15], [2, 6], [2, 6, 16], [2, 6, 16, 17], [2, 6, 16, 17, 18], [2, 6, 16, 17, 18, 19], [2, 6, 16, 17, 18, 19, 20], [2, 6, 16, 17, 18, 19, 20, 21], [2, 6, 16, 17, 18, 19, 20, 21, 22], [2, 6, 16, 17, 18, 19, 20, 21, 22, 23], [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24], [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18], [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26], [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27], [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28], [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28, 29], [2, 6, 16, 

In [116]:
len(training_sequence)

942

# find the maximum length in training sequence list

In [117]:
len_list=[]

for sequence in training_sequence:
  len_list.append(len(sequence))

maximum_sequence_length=max(len_list)  # wg=hich sentence is maximum length
print(maximum_sequence_length)


62


# Padding the Sequence with zeo to equla the maximum length of Sequence

In [118]:
padding_sequence=[]

for sequence in training_sequence:
  padding_needed = maximum_sequence_length - len(sequence)
  padding_sequence.append( [0] * padding_needed + sequence)

In [119]:
padding_sequence[1]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 3]

In [120]:
print(padding_sequence)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 2, 6], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

# Convert padding sequence to tensor

In [121]:
 padded_training_sequence = torch.tensor(padding_sequence,dtype=torch.long)

In [122]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 284, 176, 285],
        [  0,   0,   0,  ..., 176, 285, 286],
        [  0,   0,   0,  ..., 285, 286, 287]])

In [123]:
len(padded_training_sequence)

942

In [124]:
padded_training_sequence.shape

torch.Size([942, 62])

# separating X and y

In [125]:
X = padded_training_sequence[:, :-1]
y = padded_training_sequence[:, 1:]

In [126]:
X.shape

torch.Size([942, 61])

In [127]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 284, 176],
        [  0,   0,   0,  ..., 284, 176, 285],
        [  0,   0,   0,  ..., 176, 285, 286]])

In [128]:
y

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 284, 176, 285],
        [  0,   0,   0,  ..., 176, 285, 286],
        [  0,   0,   0,  ..., 285, 286, 287]])

# Build dataset and dataloader

In [129]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X=X
    self.y=y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self, idx):
    return self.X[idx],self.y[idx]

In [130]:
dataset=CustomDataset(X,y)

In [131]:
len(dataset)

942

In [132]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]))

# Dataloader

In [133]:
dataloader=DataLoader(dataset,batch_size=32,shuffle=True)


In [134]:
for input,output in dataloader:
  print(input,output)


tensor([[  0,   0,   0,  ...,  22,  65, 126],
        [  0,   0,   0,  ...,   0,   0, 185],
        [  0,   0,   0,  ...,   2,  88,  95],
        ...,
        [  0,   0,   0,  ..., 266, 251, 267],
        [  0,   0,   0,  ..., 226,  73,  22],
        [  0,   0,   0,  ...,   0,   0,  21]]) tensor([[  0,   0,   0,  ...,  65, 126, 164],
        [  0,   0,   0,  ...,   0, 185,   0],
        [  0,   0,   0,  ...,  88,  95,  33],
        ...,
        [  0,   0,   0,  ..., 251, 267,  30],
        [  0,   0,   0,  ...,  73,  22,  23],
        [  0,   0,   0,  ...,   0,  21,  65]])
tensor([[  0,   0,   0,  ..., 131, 164,  28],
        [  0,   0,   0,  ...,   0,   4,   5],
        [  0,   0,   0,  ...,  27,  18,  19],
        ...,
        [  0,   0,   0,  ...,  78,  65,  86],
        [  0,   0,   0,  ...,   0,   4,   5],
        [  0,   0,   0,  ...,  94,  95,  80]]) tensor([[  0,   0,   0,  ..., 164,  28,  41],
        [  0,   0,   0,  ...,   4,   5,   2],
        [  0,   0,   0,  ...,  18,  19

# Build LSTM Model

In [136]:
 class LSTMModel(nn.Module):

  def __init__(self,input_dim,embedding_dim,hidden_dim,layer_dim):
    super().__init__()
    self.embedding=nn.Embedding(input_dim,embedding_dim)

    self.lstm=nn.LSTM(embedding_dim,hidden_dim,layer_dim,batch_first=True)

    self.fc=nn.Linear(hidden_dim,input_dim) # predict vocab_size at each step # input dim=vocab_size

  def forward(self,x):
    embedded=self.embedding(x) # # (batch, seq_len, embedding_dim)
    output,(final_hidden_state,final_cell_state)=self.lstm(embedded) #  # output: (batch, seq_len, hidden_dim)
    output=self.fc(output)

    return output

In [137]:
input_dim=vocab_size
embedding_size=100
hidden_dim=150
layer_dim=2
model=LSTMModel(input_dim,embedding_size,hidden_dim,layer_dim)

# Move to GPU

In [138]:
device=torch.device("cuda" if torch.cuda.is_available() else 'cpu')
model.to(device)

LSTMModel(
  (embedding): Embedding(288, 100)
  (lstm): LSTM(100, 150, num_layers=2, batch_first=True)
  (fc): Linear(in_features=150, out_features=288, bias=True)
)

In [141]:
epochs=100
learning_rate=0.001

criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters(),lr=learning_rate)

# training Loop

In [142]:
# training Loop

for epoch in range(epochs):
  total_loss=0
  for batch_x,batch_y in dataloader:
    batch_x,batch_y=batch_x.to(device),batch_y.to(device)
    optimizer.zero_grad()
    # Pass the entire sequence through the model
    output = model(batch_x)  # output shape: (batch, seq_len, vocab_size)

    # Reshape output and target for CrossEntropyLoss
    output = output.view(-1, vocab_size) # Reshape to (batch_size * seq_len, vocab_size)
    batch_y = batch_y.view(-1) # Reshape to (batch_size * seq_len)


    loss=criterion(output,batch_y)
    loss.backward()
    optimizer.step()
    total_loss=total_loss+loss.item()
    # print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}") # Removed to avoid excessive output
  print(f"Epoch {epoch+1}/{epochs}, Total Loss: {total_loss}")

Epoch 1/100, Total Loss: 3.9944033101201057
Epoch 2/100, Total Loss: 3.7637599110603333
Epoch 3/100, Total Loss: 3.7123575508594513
Epoch 4/100, Total Loss: 3.6792823672294617
Epoch 5/100, Total Loss: 3.711744152009487
Epoch 6/100, Total Loss: 3.6270526722073555
Epoch 7/100, Total Loss: 3.60643357783556
Epoch 8/100, Total Loss: 3.608850061893463
Epoch 9/100, Total Loss: 3.62053432315588
Epoch 10/100, Total Loss: 3.5786027163267136
Epoch 11/100, Total Loss: 3.5712945610284805
Epoch 12/100, Total Loss: 3.5408926382660866
Epoch 13/100, Total Loss: 3.580262929201126
Epoch 14/100, Total Loss: 3.5510227978229523
Epoch 15/100, Total Loss: 3.542105056345463
Epoch 16/100, Total Loss: 3.5309348553419113
Epoch 17/100, Total Loss: 3.585791788995266
Epoch 18/100, Total Loss: 3.5302096903324127
Epoch 19/100, Total Loss: 3.5798360779881477
Epoch 20/100, Total Loss: 3.545292481780052
Epoch 21/100, Total Loss: 3.499551795423031
Epoch 22/100, Total Loss: 3.5419404953718185
Epoch 23/100, Total Loss: 3.50

In [ ]:
x=nn.Embedding(vocab_size,100)
y=nn.LSTM(100,150,batch_first=True)

In [ ]:
a=dataset[0][0].unsqueeze(0)

In [ ]:
x(a).shape