<a href="https://colab.research.google.com/github/minhaz1172/Neural-Network-with-PyTorch/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import torch and other libraries

In [2]:
import torch
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
torch.__version__ # check version

'2.6.0+cu124'

In [5]:
# convert inter list to tensor
ints_to_tensor=torch.tensor([0,1,2,3,4])
print(f"dtype of ints_to_tensor is {ints_to_tensor.dtype}")
ints_to_tensor

dtype of ints_to_tensor is torch.int64


tensor([0, 1, 2, 3, 4])

In [7]:
# convert float list to a tensor
floats_to_tensor=torch.tensor([0.0,4,0,2.6,4.9])
print(f"dtype of floats_to_tensor: {floats_to_tensor.dtype}")
print(f"shape of floats_to_tensor: {floats_to_tensor.shape}")
floats_to_tensor

dtype of floats_to_tensor: torch.float32
shape of floats_to_tensor: torch.Size([5])


tensor([0.0000, 4.0000, 0.0000, 2.6000, 4.9000])

In [11]:
# 2d tensor
tensor_2d=torch.tensor([[1,3,4],[4,5,6]])
print(f"dtype of tensor_2d: {tensor_2d.dtype}")
print(f"shape of tensor_2d: {tensor_2d.shape}")
tensor_2d

dtype of tensor_2d: torch.int64
shape of tensor_2d: torch.Size([2, 3])


tensor([[1, 3, 4],
        [4, 5, 6]])

In [15]:
# random tensor
random_tensor=torch.rand(2,3)# 2 by 3 matrix
print(f"dtype of random_tensor: {random_tensor.dtype}")
print(f"shape of random_tensor: {random_tensor.shape}")
random_tensor

zeros_tensor=torch.zeros(2,3)
print(f"dtype of zeros_tensor: {zeros_tensor.dtype}")
print(f"shape of zeros_tensor: {zeros_tensor.shape}")
zeros_tensor

dtype of random_tensor: torch.float32
shape of random_tensor: torch.Size([2, 3])
dtype of zeros_tensor: torch.float32
shape of zeros_tensor: torch.Size([2, 3])


tensor([[0., 0., 0.],
        [0., 0., 0.]])