<a href="https://colab.research.google.com/github/minhaz1172/Deep-Learning-with-PyTorch/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import torch and other libraries

In [1]:
import torch
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
torch.__version__ # check version

'2.6.0+cu124'

In [3]:
# convert inter list to tensor
ints_to_tensor=torch.tensor([0,1,2,3,4])
print(f"dtype of ints_to_tensor is {ints_to_tensor.dtype}")
ints_to_tensor

dtype of ints_to_tensor is torch.int64


tensor([0, 1, 2, 3, 4])

In [4]:
# convert float list to a tensor
floats_to_tensor=torch.tensor([0.0,4,0,2.6,4.9])
print(f"dtype of floats_to_tensor: {floats_to_tensor.dtype}")
print(f"shape of floats_to_tensor: {floats_to_tensor.shape}")
floats_to_tensor

dtype of floats_to_tensor: torch.float32
shape of floats_to_tensor: torch.Size([5])


tensor([0.0000, 4.0000, 0.0000, 2.6000, 4.9000])

In [5]:
# 2d tensor
tensor_2d=torch.tensor([[1,3,4],[4,5,6]])
print(f"dtype of tensor_2d: {tensor_2d.dtype}")
print(f"shape of tensor_2d: {tensor_2d.shape}")
tensor_2d

dtype of tensor_2d: torch.int64
shape of tensor_2d: torch.Size([2, 3])


tensor([[1, 3, 4],
        [4, 5, 6]])

In [6]:
# random tensor
random_tensor=torch.rand(2,3)# 2 by 3 matrix
print(f"dtype of random_tensor: {random_tensor.dtype}")
print(f"shape of random_tensor: {random_tensor.shape}")
random_tensor



dtype of random_tensor: torch.float32
shape of random_tensor: torch.Size([2, 3])


tensor([[0.9997, 0.3515, 0.6164],
        [0.3983, 0.1876, 0.5583]])

In [7]:
zeros_tensor=torch.zeros(2,3)
print(f"dtype of zeros_tensor: {zeros_tensor.dtype}")
print(f"shape of zeros_tensor: {zeros_tensor.shape}")
zeros_tensor

dtype of zeros_tensor: torch.float32
shape of zeros_tensor: torch.Size([2, 3])


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# numpy array to tensor
numpy_array=np.array([0.0,1.0,2.0,3.0])
new_tensor=torch.from_numpy(numpy_array)
print(f"dtype of new_tensor: {new_tensor.dtype}")
print(f"shape of new_tensor: {new_tensor.shape}")
new_tensor

dtype of new_tensor: torch.float64
shape of new_tensor: torch.Size([4])


tensor([0., 1., 2., 3.], dtype=torch.float64)

In [9]:
# pandas series to tensor
pandas_series=pd.Series([0.0,1.0,2.0,3.0])
new_tensor=torch.from_numpy(pandas_series.values)
print(f"dtype of new_tensor: {new_tensor.dtype}")
print(f"shape of new_tensor: {new_tensor.shape}")
new_tensor

dtype of new_tensor: torch.float64
shape of new_tensor: torch.Size([4])


tensor([0., 1., 2., 3.], dtype=torch.float64)

# Tensor operations

In [10]:
# indexing and slicing
tensor=torch.tensor([0,1,2,4,5])
tensor[3] # number 3 index

#change the value of the tensor
print(f"tensor before changing any index value,{tensor}")
tensor[3]=100
print(f"tensor after changing any index value,{tensor}")

tensor before changing any index value,tensor([0, 1, 2, 4, 5])
tensor after changing any index value,tensor([  0,   1,   2, 100,   5])


In [11]:
# slice tenspr sample
tensor1=torch.tensor([0,1,3,5,3])
sub_tensor=tensor1[1:4] #vslice element from index 1 to 4
print(f"tensor1: {tensor1}")
print(f"sub_tensor: {sub_tensor}")

tensor1: tensor([0, 1, 3, 5, 3])
sub_tensor: tensor([1, 3, 5])


In [12]:
# using arrage
torch1=torch.arange(5)
torch1


tensor([0, 1, 2, 3, 4])

In [13]:
a=torch.arange(1,10,2)  # 2 means value will rise 2
torch.max(a)

tensor(9)

In [14]:
# using linspace
torch.linspace(0,10,5) # 5means 5 values  0+10/5=2.5 ==value wil rise 2.5 each

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [15]:
# Using eye  ==unit mat'
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# Matrix multiplication

In [16]:
f=torch.tensor([[1,2,4],[3,5,7]])
f

tensor([[1, 2, 4],
        [3, 5, 7]])

In [17]:
g=torch.tensor([[1,2],[3,4],[5,6]])
g
g.shape

torch.Size([3, 2])

In [18]:
h=torch.matmul(f,g)
h

tensor([[27, 34],
        [53, 68]])

In [19]:
# vector dot product
v1=torch.tensor([5,6])
v2=torch.tensor([6,2])
torch.dot(v1,v2)

tensor(42)

In [23]:
# tanspose
torch.transpose(f)

TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


# find determinent

In [22]:
torch.det(h)

tensor(34.0000)

# special functions

In [24]:
k=torch.randint(10,(2,2),dtype=torch.float32)
k

tensor([[5., 2.],
        [5., 8.]])

In [25]:
# log
torch.log(k)

tensor([[1.6094, 0.6931],
        [1.6094, 2.0794]])

In [26]:
torch.sqrt(k)

tensor([[2.2361, 1.4142],
        [2.2361, 2.8284]])

In [27]:
torch.exp(k)

tensor([[ 148.4132,    7.3891],
        [ 148.4132, 2980.9580]])

In [28]:
# relu
torch.relu(k)

tensor([[5., 2.],
        [5., 8.]])

In [29]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.8808],
        [0.9933, 0.9997]])

In [30]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.5000, 0.0025],
        [0.5000, 0.9975]])